version: 2
updates:
  - package-ecosystem: 'cargo'
    directory: '/'
    schedule:
      interval: 'weekly'
    commit-message:
      prefix: 'fix(deps): '
    groups:
      all:
        patterns:
          - '*'