edition = "2021"
use_field_init_shorthand = true
match_block_trailing_comma = true
newline_style = "Unix"

# nightly
# imports_layout = "Horizontal"
# imports_granularity = "Module"
# normalize_comments = true
# wrap_comments = true
# reorder_impl_items = true
# group_imports = "StdExternalCrate"
# where_single_line = true