# Inspired by https://github.com/j-brn/nix-rust-template
name: CI

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v12

      - name: Cache Nix store
        uses: DeterminateSystems/magic-nix-cache-action@v6

      - name: Check flake
        run: nix flake check --accept-flake-config

  build:
    runs-on: ubuntu-latest
    needs:
      - test

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v12

      - name: Cache Nix store
        uses: DeterminateSystems/magic-nix-cache-action@v6

      - name: Build package
        run: nix build --accept-flake-config .#packages.x86_64-linux.swde

  bundle:
    runs-on: ubuntu-latest
    needs:
      - build

    strategy:
      matrix:
        bundler:
          - name: debian
            path: github:viperML/bundlers#deb
            extension: deb

          - name: docker
            path: github:viperML/bundlers#zip
            extension: zip

          - name: appimage
            path: github:ralismark/nix-appimage
            extension: AppImage

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v11

      - name: Cache Nix store
        uses: DeterminateSystems/magic-nix-cache-action@v6

      - name: Build ${{ matrix.bundler.name }} package
        run: >-
          nix bundle
          --bundler ${{ matrix.bundler.path }}
          --accept-flake-config
          --out-link result
          .#packages.x86_64-linux.swde

      - name: Prepare Bundle for upload
        run: >-
          cp
          --no-preserve=mode,ownership
          $(find -L result -type f -print -quit)
          swde-${{ github.sha }}-${{ matrix.bundler.name }}.${{ matrix.bundler.extension }}

      - name: Upload bundle
        uses: actions/upload-artifact@v4
        with:
          name: swde-${{ github.sha }}-${{ matrix.bundler.name }}
          path: swde-${{ github.sha }}-${{ matrix.bundler.name }}.${{ matrix.bundler.extension }}
